### ISSUE TITLE
Trying to understand the training on LSUN dataset with multi-class labels

### ISSUE THREAD

**Issue by prash030** [ptrblck/prog_gans_pytorch_inference#2]
Hi @ptrblck ,
Thanks for this implementation!
 
I have a question, and I was wondering if I can get your thoughts: The paper mentions that their training is unsupervised - meaning that it was not label-conditioned. Then how come they were able to generate label-specific images for LSUN dataset? Did they train separate networks for each label or is their network a multi-class generator?

Thanks in advance!

**Comment by ptrblck** [comment]
Hi @cardyfib,

as far as I know, they used label-specific images and trained separate models for each label.
You can find some of the LSUN classes in Tero Karras' [Google Drive](https://drive.google.com/drive/folders/1xeT_mPppeM7RntRHxg7F9-qUepnLcw27).

Best,
ptrblck

**Comment by prash030** [comment]
Thank you!
